version: "3.8"
services:
  backend:

    image: "tunji4physics/springboot-react-fullstack:29.8.2022.0.47.32"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev

