version: "3.8"
services:
  backend:
    image: "tunji4physics/springboot-react-fullstack:28.8.2022.21.19.36"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev

