version: "3.8"
services:
  backend:

    image: "tunji4physics/springboot-react-fullstack:1.9.2022.19.53.0"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev

