version: "3.8"
services:
  backend:

    image: "tunji4physics/springboot-react-fullstack:3.9.2022.15.8.51"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev

